apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: to-do-stset
  namespace: project
spec:
  serviceName: to-do-svc
  replicas: 1
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      volumes:
        - name: project-cache
          persistentVolumeClaim:
            claimName: project-cache-claim
      containers:
        - name: to-do-back
          image: titunidoc/devops_kubernetes:back_3.5
          env:
          - name: PORT
            value: "3001"
          - name: DB_PORT
            value: "5432"
          - name: DB_TYPE
            value: "pg"
          envFrom:
          - configMapRef:
              name: project.database
          - configMapRef:
              name: project.dbpass
          - configMapRef:
              name: project.dbuser
          - configMapRef:
              name: project.dbhost
        - name: db
          image: postgres
          ports:
            - name: web
              containerPort: 5432
          volumeMounts: 
          - name: postgres-data-storage
            mountPath: /var/lib/postgresql
            subPath: postgres
          envFrom:
          - configMapRef:
              name: project.pgpass
        - name: to-do-front
          image: titunidoc/devops_kubernetes:front_3.5
          volumeMounts:
          - name: project-cache
            mountPath: /usr/src/app/files
            subPath: cache 
          env:
          - name: PORT
            value: "3005"     
          - name: IMAGE_URL
            value: "https://picsum.photos/1200"  
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-storage
        namespace: project
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-cache-claim # name of the volume claim, this will be used in the deployment
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
