FROM node:22-alpine

WORKDIR /mydir 
RUN cat /etc/os-release
RUN apk update && apk --no-cache add curl
COPY notesfront front
RUN cd front && npm install --silent && npm run build --silent && cd .. 
RUN cp -r front/dist build && rm -r front
COPY middlewareback . 
RUN npm install
COPY db/migrations ./migrations
COPY db/knexfile.js .
CMD npx knex migrate:latest && node ./bin/www 